name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          brew install automake libtool

      - name: Configure and make
        run: |
          ./autogen.sh
          ./configure --disable-shared
          make -j4
          make check

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv .libs/libopus.a ./libopus-macos12.a
          mv COPYING LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libopus-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          brew install libtool automake
          ./autogen.sh
          ./configure --disable-shared
          make -j4
          make check

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv .libs/libopus.a ./libopus-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libopus-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.6/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Configure and make linux-x64
        run: |
          ./autogen.sh
          ./configure --disable-shared
          make -j4
          make check
          mv .libs/libopus.a ./libopus-linux-x64.a

      - name: Configure and make RPi
        run: |
          make clean
          ./configure --host=aarch64-unknown-linux-gnu --disable-shared
          make -j4
          mv .libs/libopus.a ./libopus-rpi-arm64.a
        env:
          AR: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-ar
          RANLIB: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-ranlib
          LD: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc
          CC: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libopus-rpi-arm64.a
            libopus-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-linux, build-macos-arm64]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libopus-macos12.a
            libopus-macos-arm64.a
            libopus-rpi-arm64.a
            libopus-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
