name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          brew install automake libtool

      - name: Configure and make
        run: |
          ./autogen.sh
          ./configure --disable-shared
          make -j4
          make check

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv .libs/libopus.a ./libopus-macos10.a
          mv COPYING LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos10
          path: |
            include.zip
            libopus-macos10.a
            LICENSE

  build-macos-arm64:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ./autogen.sh
          ./configure --disable-shared
          make -j4
          make check

      - name: Prepare output
        run: |
          pushd include
          zip -r ../include.zip .
          popd
          mv .libs/libopus.a ./libopus-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: libopus-macos-arm64.a

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure and make
        run: |
          ln -sf $ANDROID_NDK_ROOT $ANDROID_SDK_ROOT/ndk-bundle
          ./autogen.sh
          ./configure --host=aarch64-linux-android --disable-shared
          make -j4
          make check
        env:
          AR: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar
          RANLIB: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ranlib
          LD: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
          CC: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang

      - name: Rename build output
        run: mv .libs/libopus.a ./libopus-android30.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-android30
          path: libopus-android30.a

  create-release:
    runs-on: ubuntu-20.04
    needs: [build-macos, build-android, build-macos-arm64]
    steps:
      - name: Get build output macos10
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos10

      - name: Get build output android30
        uses: actions/download-artifact@v2
        with:
          name: build-output-android30

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libopus-macos10.a
            libopus-android30.a
            libopus-macos-arm64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
